services:
  postgres:
    image: postgres:17-alpine
    container_name: run-mishe-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-run-mishe}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-run-mishe}
      POSTGRES_DB: ${POSTGRES_DB:-run-mishe}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - run-mishe

volumes:
  postgres-data:

networks:
  run-mishe:
    name: run-mishe
